# Generated by Django 5.0.7 on 2024-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentry',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
