# Generated by Django 5.0.7 on 2024-08-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postentry_is_blocked'),
        ('users', '0002_user_auto_reply_delay_user_auto_reply_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
