# Generated by Django 5.0.7 on 2024-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
